global using Application.Interfaces;
global using Application.UseCases.Abstractions;
global using Core.Contracts;
global using Core.Enums;
global using Core.Interfaces;
global using Core.ValueObjects;
global using Core.TasksResults;
global using MediatR;
global using FluentValidation;