services:

  booktheroomdb:
    container_name: booktheroomdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BookTheRoomDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_booktheroom:/var/lib/postgresql/data/
 
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - booktheroomdb
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro